# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnf <- function(a = 0L, b = 1L) {
    .Call('shinyCpp2_rnf', PACKAGE = 'shinyCpp2', a, b)
}

sq <- function(len, start = 0L) {
    .Call('shinyCpp2_sq', PACKAGE = 'shinyCpp2', len, start)
}

nrnf <- function(n, a = 0L, b = 1L, norm = TRUE) {
    .Call('shinyCpp2_nrnf', PACKAGE = 'shinyCpp2', n, a, b, norm)
}

problemGenerator <- function(nproblem, noutcomeA, noutcomeB) {
    .Call('shinyCpp2_problemGenerator', PACKAGE = 'shinyCpp2', nproblem, noutcomeA, noutcomeB)
}

arrange <- function(opt) {
    .Call('shinyCpp2_arrange', PACKAGE = 'shinyCpp2', opt)
}

transformProblems <- function(problems, nA = 0L) {
    .Call('shinyCpp2_transformProblems', PACKAGE = 'shinyCpp2', problems, nA)
}

cump <- function(ps) {
    .Call('shinyCpp2_cump', PACKAGE = 'shinyCpp2', ps)
}

v_f <- function(v, fct, xp) {
    .Call('shinyCpp2_v_f', PACKAGE = 'shinyCpp2', v, fct, xp)
}

w_ge <- function(p, fct, xp) {
    .Call('shinyCpp2_w_ge', PACKAGE = 'shinyCpp2', p, fct, xp)
}

w_tk <- function(p, xp) {
    .Call('shinyCpp2_w_tk', PACKAGE = 'shinyCpp2', p, xp)
}

w_p <- function(p, fct, xp) {
    .Call('shinyCpp2_w_p', PACKAGE = 'shinyCpp2', p, fct, xp)
}

utility_tk <- function(par, opt) {
    .Call('shinyCpp2_utility_tk', PACKAGE = 'shinyCpp2', par, opt)
}

utility_ge <- function(par, opt) {
    .Call('shinyCpp2_utility_ge', PACKAGE = 'shinyCpp2', par, opt)
}

utility_p <- function(par, opt) {
    .Call('shinyCpp2_utility_p', PACKAGE = 'shinyCpp2', par, opt)
}

choiceRule <- function(phi, utA, utB) {
    .Call('shinyCpp2_choiceRule', PACKAGE = 'shinyCpp2', phi, utA, utB)
}

cpt_lik_tk <- function(par, problems, choices, limit = .0001) {
    .Call('shinyCpp2_cpt_lik_tk', PACKAGE = 'shinyCpp2', par, problems, choices, limit)
}

cpt_lik_ge <- function(par, problems, choices, limit = .0001) {
    .Call('shinyCpp2_cpt_lik_ge', PACKAGE = 'shinyCpp2', par, problems, choices, limit)
}

cpt_lik_p <- function(par, problems, choices, limit = .0001) {
    .Call('shinyCpp2_cpt_lik_p', PACKAGE = 'shinyCpp2', par, problems, choices, limit)
}

cpt_randchoice_tk <- function(par, problems) {
    .Call('shinyCpp2_cpt_randchoice_tk', PACKAGE = 'shinyCpp2', par, problems)
}

cpt_randchoice_ge <- function(par, problems) {
    .Call('shinyCpp2_cpt_randchoice_ge', PACKAGE = 'shinyCpp2', par, problems)
}

cpt_randchoice_p <- function(par, problems) {
    .Call('shinyCpp2_cpt_randchoice_p', PACKAGE = 'shinyCpp2', par, problems)
}

rcpp_hello_world <- function() {
    .Call('shinyCpp2_rcpp_hello_world', PACKAGE = 'shinyCpp2')
}

