# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('shinyCpp_rcpp_hello_world', PACKAGE = 'shinyCpp')
}

SUMp <- function(s) {
    .Call('shinyCpp_SUMp', PACKAGE = 'shinyCpp', s)
}

roundd <- function(x, d) {
    .Call('shinyCpp_roundd', PACKAGE = 'shinyCpp', x, d)
}

SUMpr <- function(s, sd, a = 0L, b = 100L) {
    .Call('shinyCpp_SUMpr', PACKAGE = 'shinyCpp', s, sd, a, b)
}

SUMf <- function(s, evs, sd, a = 0L, b = 100L) {
    .Call('shinyCpp_SUMf', PACKAGE = 'shinyCpp', s, evs, sd, a, b)
}

VUMp <- function(s, phi) {
    .Call('shinyCpp_VUMp', PACKAGE = 'shinyCpp', s, phi)
}

VUMpuni <- function(s, d, phia = .0001, phib = 2, nsteps = 10000) {
    .Call('shinyCpp_VUMpuni', PACKAGE = 'shinyCpp', s, d, phia, phib, nsteps)
}

VUMpr <- function(s, phi, sd, a = 0L, b = 100L) {
    .Call('shinyCpp_VUMpr', PACKAGE = 'shinyCpp', s, phi, sd, a, b)
}

VUMf <- function(s, evs, phi, sd, a = 0L, b = 100L) {
    .Call('shinyCpp_VUMf', PACKAGE = 'shinyCpp', s, evs, phi, sd, a, b)
}

SWIMp <- function(s, zeta) {
    .Call('shinyCpp_SWIMp', PACKAGE = 'shinyCpp', s, zeta)
}

SWIMpuni <- function(s, d) {
    .Call('shinyCpp_SWIMpuni', PACKAGE = 'shinyCpp', s, d)
}

SWIMpr <- function(s, zeta, sd, a = 0L, b = 100L) {
    .Call('shinyCpp_SWIMpr', PACKAGE = 'shinyCpp', s, zeta, sd, a, b)
}

SWIMf <- function(s, evs, zeta, sd, a = 0L, b = 100L) {
    .Call('shinyCpp_SWIMf', PACKAGE = 'shinyCpp', s, evs, zeta, sd, a, b)
}

maxN <- function(s) {
    .Call('shinyCpp_maxN', PACKAGE = 'shinyCpp', s)
}

rnf <- function(a = 0L, b = 1L) {
    .Call('shinyCpp_rnf', PACKAGE = 'shinyCpp', a, b)
}

nrnf <- function(n, a = 0L, b = 1L, norm = TRUE) {
    .Call('shinyCpp_nrnf', PACKAGE = 'shinyCpp', n, a, b, norm)
}

problemGenerator <- function(nproblem, noutcome, a = 0L, b = 100L) {
    .Call('shinyCpp_problemGenerator', PACKAGE = 'shinyCpp', nproblem, noutcome, a, b)
}

smpl <- function(ps) {
    .Call('shinyCpp_smpl', PACKAGE = 'shinyCpp', ps)
}

sampl <- function(pro, nsmp) {
    .Call('shinyCpp_sampl', PACKAGE = 'shinyCpp', pro, nsmp)
}

rnd <- function() {
    .Call('shinyCpp_rnd', PACKAGE = 'shinyCpp')
}

runiform <- function(n, a, b) {
    .Call('shinyCpp_runiform', PACKAGE = 'shinyCpp', n, a, b)
}

